# Generated by Django 2.2.1 on 2019-05-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braidservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pact',
            name='participants',
            field=models.TextField(blank=True),
        ),
    ]
